parameters:
    algolia.indexer.class: Algolia\AlgoliaSearchBundle\Indexer\Indexer
    algolia.indexer_subscriber.class: Algolia\AlgoliaSearchBundle\EventListener\AlgoliaSearchDoctrineEventSubscriber

services:
    algolia.indexer:
        class: "%algolia.indexer.class%"
        calls:
            - [setEnvironment, ["%kernel.environment%"]]
            - [setIndexNamePrefix, ["%algolia.index_name_prefix%"]]
            - [setApiSettings, ["%algolia.application_id%", "%algolia.api_key%", "%algolia.api_timeout%"]]
    algolia.indexer_subscriber:
        class: "%algolia.indexer_subscriber.class%"
        arguments:
            - "@algolia.indexer"
            - "%algolia.catch_log_exceptions%"
            - "@?logger"
        tags:
            - {name: doctrine.event_subscriber}
